version: "2.2"
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_DB=survey_app
      - POSTGRES_USER=survey_app
      - POSTGRES_PASSWORD=survey_app
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres: ~
